<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	 <PublishAot>true</PublishAot>
	 <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

	 <ItemGroup>
        <DirectPInvoke Include="minhook" /> 
        <NativeLibrary Include="src\lib\minhook.lib" Condition="$(RuntimeIdentifier.StartsWith('win'))" /> 
        <LinkerArg Include="/DEPENDENTLOADFLAG:0x800" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
    </ItemGroup>
	
</Project>
