<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PublishAot>true</PublishAot>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Korn" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="lib\" />
    <Folder Include="src\hooks\" />
  </ItemGroup>

</Project>
